"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import opciones from "../public/images/boton-de-lista.png";
import Image from "next/image";
import { useRouter } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });
import { Providers } from "./providers";
import React from "react";
import {
  Button,
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  NavbarMenu,
  NavbarMenuItem,
  NavbarMenuToggle,
} from "@nextui-org/react";
import Link from "next/link";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import { FloatingWhatsApp } from 'react-floating-whatsapp'
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isMenuOpen, setIsMenuOpen] = React.useState(false);

  const menuItems = ["catalogo", "contacto"];

  const router = useRouter();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header className="sm:h-16 h-16 w-full flex-row relative bg-[#415041] text-white hidden lg:flex">
            <div className="w-max h-full absolute z-10 left-0 ">
              <div className="w-max h-full flex justify-center items-center">
                <h1 className="sm:text-5xl text-3xl">USAGRO</h1>
              </div>
            </div>
            <div className="w-full h-full justify-center sm:flex hidden flex-row z-0">
              <div
                className="w-52 h-full flex justify-center items-center hover:cursor-pointer"
                onClick={() => router.push("/")}
              >
                Home
              </div>
              <div
                className="w-52 h-full flex justify-center items-center hover:cursor-pointer"
                onClick={() => router.push("/catalogo")}
              >
                Catalogo
              </div>
              <div
                className="w-52 h-full flex justify-center items-center hover:cursor-pointer"
                onClick={() => router.push("/contacto")}
              >
                Contacto
              </div>
            </div>
            <div className="w-full h-full justify-end flex sm:hidden">
              <div className="w-24 p-8 h-full flex items-center">
                <Image
                  alt="opciones"
                  src={opciones}
                  layout="responsive"
                  width={100}
                  height={100}
                  className=""
                ></Image>
              </div>
            </div>
          </header>
          <header className="lg:hidden">
            <Navbar
              onMenuOpenChange={setIsMenuOpen}
              className=" flex bg-[#415041] text-white"
            >
              <NavbarContent>
                <NavbarMenuToggle
                  aria-label={isMenuOpen ? "Close menu" : "Open menu"}
                  className="sm:hidden"
                />
                <NavbarBrand>
                  <p
                    className="font-bold text-inherit"
                    onClick={() => router.push("/")}
                  >
                    USAGRO
                  </p>
                </NavbarBrand>
              </NavbarContent>
              <NavbarMenu>
                {menuItems.map((item, index) => (
                  <NavbarMenuItem key={`${item}-${index}`}>
                    <Link
                      color="foreground"
                      className="w-full"
                      href={`/${item.toLowerCase()}`}
                      onClick={() => setIsMenuOpen(false)}
                    >
                      {item}
                    </Link>
                  </NavbarMenuItem>
                ))}
              </NavbarMenu>
            </Navbar>
          </header>
          <div>{children}</div>
      <FloatingWhatsApp phoneNumber="3536573126" accountName="USAGRO" chatMessage="Hola como estas? en que te podemos ayudar"/>
          <footer className="h-20 w-full bg-[#415041] text-white">
            Footer
          </footer>
        </Providers>
        
      </body>
      
    </html>
    
    );
  }
  