import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className="h-20 w-full bg-red-200"></header>
        
        
        <div>
          {children}
          </div>
        
        
      <footer className="h-20 w-full bg-green-200"></footer>
        </body>
    </html>
  );
}
